config/routes.rb
Rails.application.routes.draw do
  resources :bugzs
  resources :proj_users
  resources :projects
  get 'khushi/index'
  get 'manager/index'
  get 'ali/index'
  get 'wow/index'
  get 'project/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
# config/routes.rb
root to: 'wow#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bugz.rb
class Bugz < ApplicationRecord
  belongs_to :project
  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?

    if !image.blob.content_type.in?(%w(image/png image/gif))
      errors.add(:image, 'must be a PNG or GIF')
    end
  end
end

app/controllers/bugzs_controller.rb
class BugzsController < ApplicationController
  before_action :set_bugz, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /bugzs or /bugzs.json
  def index 
    @bugzs = Bugz.all
  end

  # GET /bugzs/1 or /bugzs/1.json
  def show
  end

  # GET /bugzs/new
  def new
    if current_user.user_type == 'developer'
      respond_to do |format|
        format.html { redirect_to bugzs_url, notice: "YOu Are Developer You cannot Access." }
        format.json { head :no_content }
      end
    @bugz = Bugz.new
    else
      @bugz = Bugz.new
    end
    
  end

  # GET /bugzs/1/edit
  def edit
  end

  # POST /bugzs or /bugzs.json
  def create
    @bugz = Bugz.new(bugz_params)

    respond_to do |format|
      if @bugz.save
        format.html { redirect_to bugz_url(@bugz), notice: "Bugz was successfully created." }
        format.json { render :show, status: :created, location: @bugz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bugz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugzs/1 or /bugzs/1.json
  def update
    respond_to do |format|
      if @bugz.update(bugz_params)
        format.html { redirect_to bugz_url(@bugz), notice: "Bugz was successfully updated." }
        format.json { render :show, status: :ok, location: @bugz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bugz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugzs/1 or /bugzs/1.json
  def destroy

    if current_user.user_type == 'developer'
      respond_to do |format|
        format.html { redirect_to bugzs_url, notice: "YOu Are Developer You cannot DElete  ." }
        format.json { head :no_content }
      end
    else
    @bugz.destroy!
    respond_to do |format|
      format.html { redirect_to bugzs_url, notice: "Bugz was successfully destroyed." }
      format.json { head :no_content }
    end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bugz
      @bugz = Bugz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bugz_params
      params.require(:bugz).permit(:title, :deadline, :b_type, :status, :project_id,:image)
    end
end

app/helpers/bugzs_helper.rb
module BugzsHelper
end

app/views/bugzs/_bugz.html.erb
<div id="<%= dom_id bugz %>">
  <p>
    <strong>Title:</strong>
    <%= bugz.title %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= bugz.deadline %>
  </p>
  <p>
  <strong>Image:</strong>
  <% if @bugz && @bugz.image.present? %>
    <%= image_tag @bugz.image %>
  <% else %>
    click on show to see image 
  <% end %>
</p>
  <p>
    <strong>B type:</strong>
    <%= bugz.b_type %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= bugz.status %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= bugz.project_id %>
  </p>

</div>

app/views/bugzs/_form.html.erb
<%= form_with(model: bugz) do |form| %>
  <% if bugz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bugz.errors.count, "error") %> prohibited this bugz from being saved:</h2>

      <ul>
        <% bugz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :deadline %>
  </div>
  <div class="field">
    <%= form.label :b_type %>
    <%= form.select :b_type, ['feature', 'bug'] %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['new', 'started', 'completed', 'resolved'] %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.collection_select :project_id, Project.all, :id, :name, prompt: "Select a Project" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bugzs/edit.html.erb
<h1>Editing bugz</h1>

<%= render "form", bugz: @bugz %>

<br>

<div>
  <%= link_to "Show this bugz", @bugz %> |
  <%= link_to "Back to bugzs", bugzs_path %>
</div>

app/views/bugzs/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %><%= button_to  'Logout', destroy_user_session_path, method: :delete,class: 'btn' %>


<% else %><%= link_to 'Sign up', new_user_registration_path %> <%= link_to 'Login', new_user_session_path %><% end %>

<h1>Bugzs</h1>

<div id="bugzs">
  <% @bugzs.each do |bugz| %>
    <%= render bugz %>
    <p>
      <%= link_to "Show this bugz", bugz %>
    </p>
  <% end %>
</div>

<%= link_to "New bugz", new_bugz_path %>

app/views/bugzs/new.html.erb
<h1>New bugz</h1>

<%= render "form", bugz: @bugz %>

<br>

<div>
  <%= link_to "Back to bugzs", bugzs_path %>
</div>

app/views/bugzs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bugz %>



<div>
  <%= link_to "Edit this bugz", edit_bugz_path(@bugz) %> |
  <%= link_to "Back to bugzs", bugzs_path %>

  <%= button_to "Destroy this bugz", @bugz, method: :delete %>
</div>