config/routes.rb
Rails.application.routes.draw do
  resources :bugzs
  resources :proj_users
  resources :projects
  get 'khushi/index'
  get 'manager/index'
  get 'ali/index'
  get 'wow/index'
  get 'project/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
# config/routes.rb
root to: 'wow#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :proj_users,dependent: :destroy
    accepts_nested_attributes_for :proj_users, allow_destroy: true,reject_if: :all_blank
    has_many :bugzs, dependent: :destroy, inverse_of: :project
   
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id])
    @bugzs = @project.bugzs
 
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.proj_users.build
  end

  # GET /projects/1/edit
  
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    if current_user.user_type == 'qa'
      respond_to do |format|
        format.html { redirect_to projects_url, notice: "YOu Are QA You cannot DElete Project ." }
        format.json { head :no_content }
      end
    else
    @project.destroy!
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, proj_users_attributes: [:project_id, :user_id, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, data:{
  controller: "nested-form",
  nested_form_wrapper_selector_value: '.nested-form-wrapper'
}) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <br>
  <h3>----------------------------------------</h3>
  <h1> Assign Developer/QA</h2>
  <template data-nested-form-target="template">
  <%= form.fields_for :proj_users, ProjUser.new, child_index: 'NEW_RECORD' do |projuser_fields| %>
    <%= render "projects/projuser_form", f: projuser_fields %>
  <% end %>
  </template>
  <%= form.fields_for :proj_users do |projuser_fields| %>
  <%= render "projects/projuser_form", f: projuser_fields %>
  <% end %>


  <div data-nested-form-target="target"> </div><br>
  <button type="button" data-action="nested-form#add">ADD More Users </button>
<br><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
<table border="1">
        <tr>
        <th>NAME</th>
        <th> Developer/QA </th>
      </tr>
  <tr>
  
    <td><%= project.name %></td>
    <td>
    <table border="1">
      <tr>
        <th>Their ID</th>
      </tr>
      <% project.proj_users.each do |task| %>
        <tr>
          <td><%= task.user_id %></td>
          
        </tr>
      <% end %>
    </table></td>
  </tr>
</table>
<h3>Their Bugs</h3>


<% project.bugzs.each do |bug| %>

    <p>
      <strong>Title:</strong>
      <%= bug.title %>
    </p>

    <p>
    <strong>Deadline:</strong>
    <%= bug.deadline %>
  </p>
  <p>
    <strong>Image:</strong>
    <% if @bug && @bug.image.present? %>
    <%= image_tag @bugz.image %>
  <% else %>
    click on show to see image 
  <% end %>
</p>
  <p>
    <strong>B type:</strong>
    <%= bug.b_type %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= bug.status %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= bug.project_id %>
  </p>
    


    <% end %>


</div>

app/views/projects/_projuser_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
<%= f.label :user_id %>
<%= f.collection_select(:user_id, User.where.not(user_type: 'manager'), :id, :full_name, { include_blank: "Select Developer/QA" }) %>

<button type="button" data-action="nested-form#remove"> Remove task</button>
<%= f.hidden_field :_destroy %> 

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %><%= button_to  'Logout', destroy_user_session_path, method: :delete,class: 'btn' %>


<% else %><%= link_to 'Sign up', new_user_registration_path %> <%= link_to 'Login', new_user_session_path %><% end %>
<p style="color: green"><%= notice %></p>
<h2>------------------------------------------------------Welcom Manager-----------------------------------------------  </h2>
<h1>Projects </h1>
<h3> Create BUGS <%= link_to "bug for project", new_bugz_path  %></h3>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>
<!-- app/views/projects/index.html.erb -->

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>