config/routes.rb
Rails.application.routes.draw do
  resources :bugzs
  resources :proj_users
  resources :projects
  get 'khushi/index'
  get 'manager/index'
  get 'ali/index'
  get 'wow/index'
  get 'project/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
# config/routes.rb
root to: 'wow#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/proj_user.rb
class ProjUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/proj_users_controller.rb
class ProjUsersController < ApplicationController
  before_action :set_proj_user, only: %i[ show edit update destroy ]

  # GET /proj_users or /proj_users.json
  def index
    @proj_users = ProjUser.all
  end

  # GET /proj_users/1 or /proj_users/1.json
  def show
  end

  # GET /proj_users/new
  def new
    @proj_user = ProjUser.new
  end

  # GET /proj_users/1/edit
  def edit
  end

  # POST /proj_users or /proj_users.json
  def create
    @proj_user = ProjUser.new(proj_user_params)

    respond_to do |format|
      if @proj_user.save
        format.html { redirect_to proj_user_url(@proj_user), notice: "Proj user was successfully created." }
        format.json { render :show, status: :created, location: @proj_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proj_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proj_users/1 or /proj_users/1.json
  def update
    respond_to do |format|
      if @proj_user.update(proj_user_params)
        format.html { redirect_to proj_user_url(@proj_user), notice: "Proj user was successfully updated." }
        format.json { render :show, status: :ok, location: @proj_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proj_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proj_users/1 or /proj_users/1.json
  def destroy
    @proj_user.destroy!

    respond_to do |format|
      format.html { redirect_to proj_users_url, notice: "Proj user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proj_user
      @proj_user = ProjUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proj_user_params
      params.require(:proj_user).permit(:project_id, :user_id)
    end
end

app/helpers/proj_users_helper.rb
module ProjUsersHelper
end

app/views/proj_users/_form.html.erb
<%= form_with(model: proj_user) do |form| %>
  <% if proj_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proj_user.errors.count, "error") %> prohibited this proj_user from being saved:</h2>

      <ul>
        <% proj_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/proj_users/_proj_user.html.erb
<div id="<%= dom_id proj_user %>">
  <p>
    <strong>Project:</strong>
    <%= proj_user.project_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= proj_user.user_id %>
  </p>

</div>

app/views/proj_users/edit.html.erb
<h1>Editing proj user</h1>

<%= render "form", proj_user: @proj_user %>

<br>

<div>
  <%= link_to "Show this proj user", @proj_user %> |
  <%= link_to "Back to proj users", proj_users_path %>
</div>

app/views/proj_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Proj users</h1>

<div id="proj_users">
  <% @proj_users.each do |proj_user| %>
    <%= render proj_user %>
    <p>
      <%= link_to "Show this proj user", proj_user %>
    </p>
  <% end %>
</div>

<%= link_to "New proj user", new_proj_user_path %>

app/views/proj_users/new.html.erb
<h1>New proj user</h1>

<%= render "form", proj_user: @proj_user %>

<br>

<div>
  <%= link_to "Back to proj users", proj_users_path %>
</div>

app/views/proj_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @proj_user %>

<div>
  <%= link_to "Edit this proj user", edit_proj_user_path(@proj_user) %> |
  <%= link_to "Back to proj users", proj_users_path %>

  <%= button_to "Destroy this proj user", @proj_user, method: :delete %>
</div>