config/routes.rb
Rails.application.routes.draw do
  resources :bugzs
  resources :proj_users
  resources :projects
  get 'khushi/index'
  get 'manager/index'
  get 'ali/index'
  get 'wow/index'
  get 'project/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
# config/routes.rb
root to: 'wow#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/views/project_users/_form.html.erb
<%= form_with(model: project_user) do |form| %>
  <% if project_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_user.errors.count, "error") %> prohibited this project_user from being saved:</h2>

      <ul>
        <% project_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/project_users/_project_user.html.erb
<div id="<%= dom_id project_user %>">
  <p>
    <strong>Project:</strong>
    <%= project_user.project_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project_user.user_id %>
  </p>

</div>

app/views/project_users/edit.html.erb
<h1>Editing project user</h1>

<%= render "form", project_user: @project_user %>

<br>

<div>
  <%= link_to "Show this project user", @project_user %> |
  <%= link_to "Back to project users", project_users_path %>
</div>

app/views/project_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Project users</h1>

<div id="project_users">
  <% @project_users.each do |project_user| %>
    <%= render project_user %>
    <p>
      <%= link_to "Show this project user", project_user %>
    </p>
  <% end %>
</div>

<%= link_to "New project user", new_project_user_path %>

app/views/project_users/new.html.erb
<h1>New project user</h1>

<%= render "form", project_user: @project_user %>

<br>

<div>
  <%= link_to "Back to project users", project_users_path %>
</div>

app/views/project_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project_user %>

<div>
  <%= link_to "Edit this project user", edit_project_user_path(@project_user) %> |
  <%= link_to "Back to project users", project_users_path %>

  <%= button_to "Destroy this project user", @project_user, method: :delete %>
</div>